parent_version: 
  - version_name: 2.6
    version_number:  
no_build: False
no_repo: False
variables:
  - name: "cicd_gmcd_token"
    type: env
    default: "CICD_GMCD_TOKEN"
  - name: "gitlab_domain"
    type: env
    default: "GITLAB_DOMAIN"
  - name: "docker_tools_path"
    type: env
    default: "DOCKER_TOOLS_PATH"
  - name: "cicd_unit_test_path"
    type: env
    default: "CICD_UNIT_TEST_PATH"
  - name: "git_image_name"
    type: env
    default: "GIT_IMAGE_NAME"
  - name: "git_image_tag"
    type: env
    default: "GIT_IMAGE_TAG"
  - name: "deploy_group_id"
    type: env
    default: "DEPLOY_GROUP_ID"
    