parent_version: 
  - version_name: "3.9-bookworm"
    version_number:  
no_build: False
no_repo: False
variables:
  - name: "gitlab_domain"
    type: env
    default: "GITLAB_DOMAIN"
  - name: "docker_tools_path"
    type: env
    default: "DOCKER_TOOLS_PATH"
  - name: "cicd_unit_test_path"
    type: env
    default: "CICD_UNIT_TEST_PATH"
  - name: "registry_git_image_path"
    type: env
    default: "REGISTRY_GIT_IMAGE_PATH"
  - name: "git_image_name"
    type: env
    default: "GIT_IMAGE_NAME"
  - name: "git_image_tag"
    type: env
    default: "GIT_IMAGE_TAG"